#!/usr/bin/env node
/* sync.mjs — single source of truth for writeups.
 *
 * Reads content/writeups/*.md (YAML-ish frontmatter + markdown/HTML body),
 * converts each body to HTML via `marked`, and regenerates js/writeups.js.
 *
 * Authoring a new writeup = drop a .md file in content/writeups/. Filenames
 * are sorted lexically, so a NNN- numeric prefix controls report order.
 *
 * Frontmatter values are JSON scalars/arrays (quoted strings, [..] lists,
 * bare numbers/booleans) so they round-trip losslessly. Supported keys:
 *   slug, title, platform, difficulty, category[], date, minutes,
 *   visible (default true), tldr, format (optional), source_url (optional).
 *
 * format: "html" emits the body verbatim (used by the migrated legacy
 * writeups, whose bodies are already hand-written HTML). Omit it (or set
 * "markdown") to author in markdown — the default going forward.
 *
 * If `source_url` is set, the body is fetched from that raw-markdown URL at
 * build time (lets writeups live in the Learnings repo yet render here);
 * any local body below the frontmatter is used as a fallback on fetch fail.
 *
 * Run: node tools/sync.mjs   (or `npm run sync` to also rebuild og/feed).
 */
import { marked } from "marked";
import fs from "node:fs";
import path from "node:path";

const DIR = "content/writeups";
const OUT = "js/writeups.js";

const escHtml = (s) =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

/* fenced code -> the <pre class="code"> markup the site + copy-buttons expect */
marked.use({
  renderer: {
    code(token) {
      const text = typeof token === "object" ? token.text : token;
      const lang = (typeof token === "object" ? token.lang : arguments[1]) || "";
      const attr = lang ? ` data-lang="${escHtml(lang.split(/\s+/)[0])}"` : "";
      return `<pre class="code"${attr}><code>${escHtml(text)}</code></pre>\n`;
    },
  },
});

function parseFrontmatter(raw) {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!m) throw new Error("missing frontmatter");
  const meta = {};
  for (const line of m[1].split(/\r?\n/)) {
    if (!line.trim() || /^\s*#/.test(line)) continue;
    const i = line.indexOf(":");
    if (i === -1) continue;
    const key = line.slice(0, i).trim();
    const rawVal = line.slice(i + 1).trim();
    let val;
    try {
      val = JSON.parse(rawVal);
    } catch {
      val = rawVal.replace(/^['"]|['"]$/g, "");
    }
    meta[key] = val;
  }
  return { meta, body: m[2] };
}

async function resolveBody(meta, localBody) {
  if (!meta.source_url) return localBody;
  try {
    const res = await fetch(meta.source_url);
    if (!res.ok) throw new Error("HTTP " + res.status);
    return await res.text();
  } catch (e) {
    console.warn(`  ! source_url fetch failed for ${meta.slug} (${e.message}); using local body`);
    return localBody;
  }
}

function toHtml(body, format) {
  if (format === "html") return body.trim();
  const html = marked.parse(body, { async: false });
  return html.trim();
}

async function main() {
  const files = fs
    .readdirSync(DIR)
    .filter((f) => f.endsWith(".md"))
    .sort();

  const entries = [];
  const seen = new Set();
  for (const f of files) {
    const raw = fs.readFileSync(path.join(DIR, f), "utf8");
    const { meta, body } = parseFrontmatter(raw);
    if (!meta.slug) throw new Error(`${f}: frontmatter missing "slug"`);
    if (seen.has(meta.slug)) throw new Error(`duplicate slug "${meta.slug}" (${f})`);
    seen.add(meta.slug);

    const resolved = await resolveBody(meta, body);
    entries.push({
      slug: meta.slug,
      title: meta.title,
      platform: meta.platform,
      difficulty: meta.difficulty,
      category: meta.category || [],
      date: meta.date,
      minutes: meta.minutes,
      visible: meta.visible !== false,
      tldr: meta.tldr,
      content: toHtml(resolved, meta.format),
    });
  }

  const banner =
    "/* AUTO-GENERATED by tools/sync.mjs from content/writeups/*.md — do not edit by hand.\n" +
    "   Add or edit a writeup: create/modify a markdown file in content/writeups/, then `npm run sync`. */\n";
  const js = banner + "const WRITEUPS = " + JSON.stringify(entries, null, 2) + ";\n";
  fs.writeFileSync(OUT, js);
  console.log(`synced ${entries.length} writeups -> ${OUT}`);
}

main().catch((e) => {
  console.error("sync failed:", e.message);
  process.exit(1);
});
